export const NEW_POST_TITLE_CHANGE_VALUE = "NEW_TITLE_CHANGE_VALUE";
export const NEW_POST_BODY_CHANGE_VALUE = "NEW_BODY_CHANGE_VALUE";
export const POST_USER_COMMENT = "POST_USER_COMMENT";
export const GET_COMMENTS = "GET_COMMENTS";
